### ISSUE TITLE
Pre-Processor Test Plan jsessionid is blank in each request

### ISSUE THREAD

**Issue by izaac** [jmeterbyexample/jmeter-test-scripts#1]
Hello, 

I'm following your book and got up to the chapter about the pre-processors specifically the HTTP URL Re-writing Modifier I start the web application on localhost and start the test. 

Then I check the Order History as described at the end of the steps of section 8.1 of the book. No history is recorded. I check the Jetty server log and noticed:

session id --> null

After that I've taken a closer look to the requests sent by JMeter and I notice the jsessionid= parameter is sent blank. For example:

 http://localhost:8080/order/placeOrder;jsessionid=

I'm using JMeter 3.1

**Comment by saimatam** [comment]
Izaac,

Certain Web Servers do not support sessions in Cookies. They expect the sessionid as a part of URL. Only in such cases you would need URL rewriting.

This example in section **8.1 HTTP URL Re-writing Modifier** expects the URL to have sessionid. The **dt** application needs to be run with a special environment variable **SESSION_IN_URL** set to **true**

Please look at the **Appendix B**.

**B.1.2. Start With URL ReWriting Enabled**
```
$ export SESSION_IN_URL=true
$ ./startDt.sh
```

Let me know if this solved your issue.

regards,
Sai Matam

**Comment by izaac** [comment]
@saimatam thank you, this resolved the issue I was having. 

I didn't see any reference to Appendix B in Chapter 8 or I might've missed it somehow. 

Regards,
izaac

**Comment by saimatam** [comment]
Izaac,

Thank you for the feedback. When we correct the book next time, we will 
put a special note and ask readers to refer Appendix B.

I would appreciate if you can write a review on Amazon or LeanPub - wherever
you bought the book.

regards,
Sai Matam
